name: Program can pass all tests
# a test that the program can compile, run and terminate

on:
  pull_request:

jobs:
  can_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: remove binary (bin) folder
      run: |
        rm -rf bin

    - name: add binary (bin) folder
      run: |
        mkdir bin

    - name: compile main.c
      run: |
        gcc src/main.c -o bin/a.exe -lm

    - name: run debugTest1
      run: |
        bin/a.exe debugTest1